// <auto-generated />
using System;
using Cligen.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cligen.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(CligenDbContext))]
    partial class CligenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cligen.Dominio.Entidades.Exame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataLiberacaoPrevista")
                        .HasColumnType("date");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid>("ExameCatalogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExcluidoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoExclusao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeMedicoExterno")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<int>("TipoMedico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("AtualizadoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("Estado");

                    b.HasIndex("ExameCatalogoId");

                    b.HasIndex("ExcluidoPorId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("Exame", (string)null);
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.ExameCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrazoExecucaoDias")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoReferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("ExameCatalogo", (string)null);
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("AtualizadoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("Nome");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.Parametro", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Chave");

                    b.ToTable("Parametro", (string)null);

                    b.HasData(
                        new
                        {
                            Chave = "DiasRevisao",
                            Valor = "3"
                        });
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<int>("TipoLogin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasFilter("[GoogleSubjectId] IS NOT NULL");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.Exame", b =>
                {
                    b.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cligen.Dominio.Entidades.ExameCatalogo", null)
                        .WithMany()
                        .HasForeignKey("ExameCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ExcluidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cligen.Dominio.Entidades.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Cligen.Dominio.Entidades.Amostra", "Amostras", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataAcolhimento")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("DataLiberacaoPrevista")
                                .HasColumnType("date");

                            b1.Property<int>("DiasRevisao")
                                .HasColumnType("int");

                            b1.Property<Guid>("ExameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("MotivoRejeicao")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("PrazoExecucaoDias")
                                .HasColumnType("int");

                            b1.Property<bool>("Recoleta")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("RegistradoEm")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("RegistradoPorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("RejeitadaEm")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("RejeitadaPorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ExameId");

                            b1.HasIndex("RegistradoPorId");

                            b1.HasIndex("RejeitadaPorId");

                            b1.ToTable("Amostra", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExameId");

                            b1.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                                .WithMany()
                                .HasForeignKey("RegistradoPorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                                .WithMany()
                                .HasForeignKey("RejeitadaPorId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsMany("Cligen.Dominio.Entidades.Anexo", "Anexos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Caminho")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime>("EnviadoEm")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("EnviadoPorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ExameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HashSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("char(64)")
                                .IsFixedLength();

                            b1.Property<string>("NomeOriginal")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<DateTime?>("RemovidoEm")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("RemovidoPorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("TamanhoBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("TipoConteudo")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("EnviadoPorId");

                            b1.HasIndex("ExameId");

                            b1.HasIndex("RemovidoPorId");

                            b1.ToTable("Anexo", (string)null);

                            b1.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                                .WithMany()
                                .HasForeignKey("EnviadoPorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ExameId");

                            b1.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                                .WithMany()
                                .HasForeignKey("RemovidoPorId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("Amostras");

                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("Cligen.Dominio.Entidades.Paciente", b =>
                {
                    b.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cligen.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Cligen.Dominio.Entidades.ResponsavelLegal", "ResponsavelLegal", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("NumeroDocumento")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Parentesco")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("TipoDocumento")
                                .HasColumnType("int");

                            b1.HasKey("PacienteId");

                            b1.ToTable("ResponsavelLegal", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("ResponsavelLegal");
                });
#pragma warning restore 612, 618
        }
    }
}
